print("-"*40)
print("Tugas 1 Kelas-B")
print("-"*40)
print("Nama : Dandi Nur Faizi")
print("NPM  : 20183010078")
print("-"*40)
print("Notes:")
print("-"*40)
print("Halo dunia")
print("ini adalah script python pertamaku di linux")
